server:
  port: 6010

spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://localhost:5432/parqueo
    username: usertest
    password: 123456

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arquitectura-de-Software-02-2023/server-config.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8714/eureka/
